apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ingress.toroponz.io
  resources:
  - dynamicingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress.toroponz.io
  resources:
  - dynamicingresses/finalizers
  verbs:
  - update
- apiGroups:
  - ingress.toroponz.io
  resources:
  - dynamicingresses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ingress.toroponz.io
  resources:
  - dynamicingressstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingress.toroponz.io
  resources:
  - dynamicingressstates/finalizers
  verbs:
  - update
- apiGroups:
  - ingress.toroponz.io
  resources:
  - dynamicingressstates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dynamic-ingress-operator
    app.kubernetes.io/part-of: dynamic-ingress-operator
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'