apiVersion: ingress.toroponz.io/v1
kind: DynamicIngress
metadata:
  labels:
    app.kubernetes.io/name: dynamicingress
    app.kubernetes.io/instance: dynamicingress-sample
    app.kubernetes.io/part-of: dynamic-ingress-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dynamic-ingress-operator
  name: dynamic-ingress-sample
  namespace: dynamic-ingress-operator-system
spec:
  target: dynamic-created-ingress
  passiveIngress: null
    # template:
    #   metadata:
    #     annotations: {}
    #     labels: {}
    #   spec: {}
  activeIngress:
    template:
      metadata:
        annotations:
          alb.ingress.kubernetes.io/group.name: test
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/target-type: ip
          kubernetes.io/ingress.class: alb
        labels:
          app.kubernetes.io/name: test
      spec:
        rules:
          - http:
              paths:
                - backend:
                    service:
                      name: test-service
                      port:
                        number: 80
                  pathType: ImplementationSpecific
  state: dynamic-ingress-state-sample
  expected:
    status: 200
    body: '{"status":"ok"}'
    compareType: json
    # compareType: plaintext
    comparePolicy: contains
    # comparePolicy: strict
  errorPolicy: retain
  # errorPolicy: passive
  # errorPolicy: active
