apiVersion: ingress.toroponz.io/v1
kind: DynamicIngressState
metadata:
  labels:
    app.kubernetes.io/name: dynamicingressstate
    app.kubernetes.io/instance: dynamicingressstate-sample
    app.kubernetes.io/part-of: dynamic-ingress-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dynamic-ingress-operator
  name: dynamic-ingress-state-sample
spec:
  probe:
    type: HTTP
    method: GET
    url: https://toro-ponz.github.io/health
  # fixedResponse:
  #   status: 200
  #   body: |
  #     {
  #       "status":"ok",
  #       "time":"2024-01-01 10:00:00"
  #     }
